version: '3.9'

services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - "27017:27017"
  node-user-app:
    depends_on:
      - mongodb
    build: .
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "3020:3020"
    environment:
      - NODE_PORT=3020
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT

volumes:
  node-mongo-data: